/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const HabitType = IDL.Variant({
  'text' : IDL.Null,
  'boolean' : IDL.Null,
  'numeric' : IDL.Null,
});
export const Frequency = IDL.Variant({
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const Habit = IDL.Record({
  'id' : IDL.Nat,
  'icon' : IDL.Nat8,
  'habitType' : HabitType,
  'name' : IDL.Text,
  'createdAt' : Time,
  'color' : IDL.Text,
  'unit' : IDL.Text,
  'target' : IDL.Nat,
  'frequency' : Frequency,
});
export const LogEntry = IDL.Record({
  'value' : IDL.Text,
  'date' : Time,
  'habitId' : IDL.Nat,
  'notes' : IDL.Text,
});
export const BorderRadius = IDL.Variant({
  'none' : IDL.Null,
  'pill' : IDL.Null,
  'large' : IDL.Null,
  'small' : IDL.Null,
});
export const CardStyle = IDL.Variant({
  'shadow' : IDL.Null,
  'flat' : IDL.Null,
  'glass' : IDL.Null,
});
export const Theme = IDL.Record({
  'backgroundColor' : IDL.Text,
  'borderRadius' : BorderRadius,
  'primaryColor' : IDL.Text,
  'accentColor' : IDL.Text,
  'cardStyle' : CardStyle,
});

export const idlService = IDL.Service({
  'addLogEntry' : IDL.Func([IDL.Nat, Time, IDL.Text, IDL.Text], [], []),
  'createHabit' : IDL.Func(
      [IDL.Text, HabitType, IDL.Text, IDL.Nat8, IDL.Text, IDL.Nat, Frequency],
      [IDL.Nat],
      [],
    ),
  'deleteHabit' : IDL.Func([IDL.Nat], [], []),
  'deleteLogEntry' : IDL.Func([IDL.Nat, Time], [], []),
  'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getHabit' : IDL.Func([IDL.Nat], [Habit], ['query']),
  'getLogEntriesByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(LogEntry)],
      ['query'],
    ),
  'getLogEntriesByHabitAndDateRange' : IDL.Func(
      [IDL.Nat, Time, Time],
      [IDL.Vec(LogEntry)],
      ['query'],
    ),
  'getLogEntriesForHabit' : IDL.Func([IDL.Nat], [IDL.Vec(LogEntry)], ['query']),
  'getTheme' : IDL.Func([], [IDL.Opt(Theme)], ['query']),
  'saveTheme' : IDL.Func([Theme], [], []),
  'updateHabit' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat8, IDL.Text, IDL.Nat, Frequency],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const HabitType = IDL.Variant({
    'text' : IDL.Null,
    'boolean' : IDL.Null,
    'numeric' : IDL.Null,
  });
  const Frequency = IDL.Variant({
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const Habit = IDL.Record({
    'id' : IDL.Nat,
    'icon' : IDL.Nat8,
    'habitType' : HabitType,
    'name' : IDL.Text,
    'createdAt' : Time,
    'color' : IDL.Text,
    'unit' : IDL.Text,
    'target' : IDL.Nat,
    'frequency' : Frequency,
  });
  const LogEntry = IDL.Record({
    'value' : IDL.Text,
    'date' : Time,
    'habitId' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const BorderRadius = IDL.Variant({
    'none' : IDL.Null,
    'pill' : IDL.Null,
    'large' : IDL.Null,
    'small' : IDL.Null,
  });
  const CardStyle = IDL.Variant({
    'shadow' : IDL.Null,
    'flat' : IDL.Null,
    'glass' : IDL.Null,
  });
  const Theme = IDL.Record({
    'backgroundColor' : IDL.Text,
    'borderRadius' : BorderRadius,
    'primaryColor' : IDL.Text,
    'accentColor' : IDL.Text,
    'cardStyle' : CardStyle,
  });
  
  return IDL.Service({
    'addLogEntry' : IDL.Func([IDL.Nat, Time, IDL.Text, IDL.Text], [], []),
    'createHabit' : IDL.Func(
        [IDL.Text, HabitType, IDL.Text, IDL.Nat8, IDL.Text, IDL.Nat, Frequency],
        [IDL.Nat],
        [],
      ),
    'deleteHabit' : IDL.Func([IDL.Nat], [], []),
    'deleteLogEntry' : IDL.Func([IDL.Nat, Time], [], []),
    'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getHabit' : IDL.Func([IDL.Nat], [Habit], ['query']),
    'getLogEntriesByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(LogEntry)],
        ['query'],
      ),
    'getLogEntriesByHabitAndDateRange' : IDL.Func(
        [IDL.Nat, Time, Time],
        [IDL.Vec(LogEntry)],
        ['query'],
      ),
    'getLogEntriesForHabit' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LogEntry)],
        ['query'],
      ),
    'getTheme' : IDL.Func([], [IDL.Opt(Theme)], ['query']),
    'saveTheme' : IDL.Func([Theme], [], []),
    'updateHabit' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat8, IDL.Text, IDL.Nat, Frequency],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };