/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@dfinity/agent';
import type { IDL } from '@dfinity/candid';
import type { Principal } from '@dfinity/principal';

export type BorderRadius = { 'none' : null } |
  { 'pill' : null } |
  { 'large' : null } |
  { 'small' : null };
export type CardStyle = { 'shadow' : null } |
  { 'flat' : null } |
  { 'glass' : null };
export type Frequency = { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface Habit {
  'id' : bigint,
  'icon' : number,
  'habitType' : HabitType,
  'name' : string,
  'createdAt' : Time,
  'color' : string,
  'unit' : string,
  'target' : bigint,
  'frequency' : Frequency,
}
export type HabitType = { 'text' : null } |
  { 'boolean' : null } |
  { 'numeric' : null };
export interface LogEntry {
  'value' : string,
  'date' : Time,
  'habitId' : bigint,
  'notes' : string,
}
export interface Theme {
  'backgroundColor' : string,
  'borderRadius' : BorderRadius,
  'primaryColor' : string,
  'accentColor' : string,
  'cardStyle' : CardStyle,
}
export type Time = bigint;
export interface _SERVICE {
  'addLogEntry' : ActorMethod<[bigint, Time, string, string], undefined>,
  'createHabit' : ActorMethod<
    [string, HabitType, string, number, string, bigint, Frequency],
    bigint
  >,
  'deleteHabit' : ActorMethod<[bigint], undefined>,
  'deleteLogEntry' : ActorMethod<[bigint, Time], undefined>,
  'getAllHabits' : ActorMethod<[], Array<Habit>>,
  'getHabit' : ActorMethod<[bigint], Habit>,
  'getLogEntriesByDateRange' : ActorMethod<[Time, Time], Array<LogEntry>>,
  'getLogEntriesByHabitAndDateRange' : ActorMethod<
    [bigint, Time, Time],
    Array<LogEntry>
  >,
  'getLogEntriesForHabit' : ActorMethod<[bigint], Array<LogEntry>>,
  'getTheme' : ActorMethod<[], [] | [Theme]>,
  'saveTheme' : ActorMethod<[Theme], undefined>,
  'updateHabit' : ActorMethod<
    [bigint, string, string, number, string, bigint, Frequency],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];