/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@dfinity/agent";
import type { Principal } from "@dfinity/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LogEntry {
    value: string;
    date: Time;
    habitId: bigint;
    notes: string;
}
export type Time = bigint;
export interface Habit {
    id: bigint;
    icon: number;
    habitType: HabitType;
    name: string;
    createdAt: Time;
    color: string;
    unit: string;
    target: bigint;
    frequency: Frequency;
}
export interface Theme {
    backgroundColor: string;
    borderRadius: BorderRadius;
    primaryColor: string;
    accentColor: string;
    cardStyle: CardStyle;
}
export enum BorderRadius {
    none = "none",
    pill = "pill",
    large = "large",
    small = "small"
}
export enum CardStyle {
    shadow = "shadow",
    flat = "flat",
    glass = "glass"
}
export enum Frequency {
    monthly = "monthly",
    daily = "daily",
    weekly = "weekly"
}
export enum HabitType {
    text = "text",
    boolean_ = "boolean",
    numeric = "numeric"
}
export interface backendInterface {
    addLogEntry(habitId: bigint, date: Time, value: string, notes: string): Promise<void>;
    createHabit(name: string, habitType: HabitType, unit: string, icon: number, color: string, target: bigint, frequency: Frequency): Promise<bigint>;
    deleteHabit(id: bigint): Promise<void>;
    deleteLogEntry(habitId: bigint, date: Time): Promise<void>;
    getAllHabits(): Promise<Array<Habit>>;
    getHabit(id: bigint): Promise<Habit>;
    getLogEntriesByDateRange(startDate: Time, endDate: Time): Promise<Array<LogEntry>>;
    getLogEntriesByHabitAndDateRange(habitId: bigint, startDate: Time, endDate: Time): Promise<Array<LogEntry>>;
    getLogEntriesForHabit(habitId: bigint): Promise<Array<LogEntry>>;
    getTheme(): Promise<Theme | null>;
    saveTheme(newTheme: Theme): Promise<void>;
    updateHabit(id: bigint, name: string, unit: string, icon: number, color: string, target: bigint, frequency: Frequency): Promise<void>;
}
import type { BorderRadius as _BorderRadius, CardStyle as _CardStyle, Frequency as _Frequency, Habit as _Habit, HabitType as _HabitType, Theme as _Theme, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addLogEntry(arg0: bigint, arg1: Time, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLogEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLogEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createHabit(arg0: string, arg1: HabitType, arg2: string, arg3: number, arg4: string, arg5: bigint, arg6: Frequency): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createHabit(arg0, to_candid_HabitType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, to_candid_Frequency_n3(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHabit(arg0, to_candid_HabitType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, to_candid_Frequency_n3(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async deleteHabit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHabit(arg0);
            return result;
        }
    }
    async deleteLogEntry(arg0: bigint, arg1: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLogEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLogEntry(arg0, arg1);
            return result;
        }
    }
    async getAllHabits(): Promise<Array<Habit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHabits();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHabits();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHabit(arg0: bigint): Promise<Habit> {
        if (this.processError) {
            try {
                const result = await this.actor.getHabit(arg0);
                return from_candid_Habit_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHabit(arg0);
            return from_candid_Habit_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogEntriesByDateRange(arg0: Time, arg1: Time): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogEntriesByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogEntriesByDateRange(arg0, arg1);
            return result;
        }
    }
    async getLogEntriesByHabitAndDateRange(arg0: bigint, arg1: Time, arg2: Time): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogEntriesByHabitAndDateRange(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogEntriesByHabitAndDateRange(arg0, arg1, arg2);
            return result;
        }
    }
    async getLogEntriesForHabit(arg0: bigint): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogEntriesForHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogEntriesForHabit(arg0);
            return result;
        }
    }
    async getTheme(): Promise<Theme | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTheme();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTheme();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveTheme(arg0: Theme): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveTheme(to_candid_Theme_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveTheme(to_candid_Theme_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateHabit(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: string, arg5: bigint, arg6: Frequency): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHabit(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Frequency_n3(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHabit(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Frequency_n3(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
}
function from_candid_BorderRadius_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BorderRadius): BorderRadius {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CardStyle_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CardStyle): CardStyle {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Frequency_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Frequency): Frequency {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_HabitType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HabitType): HabitType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Habit_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Habit): Habit {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Theme_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Theme): Theme {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Theme]): Theme | null {
    return value.length === 0 ? null : from_candid_Theme_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    backgroundColor: string;
    borderRadius: _BorderRadius;
    primaryColor: string;
    accentColor: string;
    cardStyle: _CardStyle;
}): {
    backgroundColor: string;
    borderRadius: BorderRadius;
    primaryColor: string;
    accentColor: string;
    cardStyle: CardStyle;
} {
    return {
        backgroundColor: value.backgroundColor,
        borderRadius: from_candid_BorderRadius_n15(_uploadFile, _downloadFile, value.borderRadius),
        primaryColor: value.primaryColor,
        accentColor: value.accentColor,
        cardStyle: from_candid_CardStyle_n17(_uploadFile, _downloadFile, value.cardStyle)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    icon: number;
    habitType: _HabitType;
    name: string;
    createdAt: _Time;
    color: string;
    unit: string;
    target: bigint;
    frequency: _Frequency;
}): {
    id: bigint;
    icon: number;
    habitType: HabitType;
    name: string;
    createdAt: Time;
    color: string;
    unit: string;
    target: bigint;
    frequency: Frequency;
} {
    return {
        id: value.id,
        icon: value.icon,
        habitType: from_candid_HabitType_n8(_uploadFile, _downloadFile, value.habitType),
        name: value.name,
        createdAt: value.createdAt,
        color: value.color,
        unit: value.unit,
        target: value.target,
        frequency: from_candid_Frequency_n10(_uploadFile, _downloadFile, value.frequency)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
}): Frequency {
    return "monthly" in value ? Frequency.monthly : "daily" in value ? Frequency.daily : "weekly" in value ? Frequency.weekly : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    none: null;
} | {
    pill: null;
} | {
    large: null;
} | {
    small: null;
}): BorderRadius {
    return "none" in value ? BorderRadius.none : "pill" in value ? BorderRadius.pill : "large" in value ? BorderRadius.large : "small" in value ? BorderRadius.small : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shadow: null;
} | {
    flat: null;
} | {
    glass: null;
}): CardStyle {
    return "shadow" in value ? CardStyle.shadow : "flat" in value ? CardStyle.flat : "glass" in value ? CardStyle.glass : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: null;
} | {
    boolean: null;
} | {
    numeric: null;
}): HabitType {
    return "text" in value ? HabitType.text : "boolean" in value ? HabitType.boolean : "numeric" in value ? HabitType.numeric : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Habit>): Array<Habit> {
    return value.map((x)=>from_candid_Habit_n6(_uploadFile, _downloadFile, x));
}
function to_candid_BorderRadius_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BorderRadius): _BorderRadius {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_CardStyle_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardStyle): _CardStyle {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Frequency_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frequency): _Frequency {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_HabitType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HabitType): _HabitType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Theme_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): _Theme {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    backgroundColor: string;
    borderRadius: BorderRadius;
    primaryColor: string;
    accentColor: string;
    cardStyle: CardStyle;
}): {
    backgroundColor: string;
    borderRadius: _BorderRadius;
    primaryColor: string;
    accentColor: string;
    cardStyle: _CardStyle;
} {
    return {
        backgroundColor: value.backgroundColor,
        borderRadius: to_candid_BorderRadius_n21(_uploadFile, _downloadFile, value.borderRadius),
        primaryColor: value.primaryColor,
        accentColor: value.accentColor,
        cardStyle: to_candid_CardStyle_n23(_uploadFile, _downloadFile, value.cardStyle)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HabitType): {
    text: null;
} | {
    boolean: null;
} | {
    numeric: null;
} {
    return value == HabitType.text ? {
        text: null
    } : value == HabitType.boolean ? {
        boolean_: null
    } : value == HabitType.numeric ? {
        numeric: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BorderRadius): {
    none: null;
} | {
    pill: null;
} | {
    large: null;
} | {
    small: null;
} {
    return value == BorderRadius.none ? {
        none: null
    } : value == BorderRadius.pill ? {
        pill: null
    } : value == BorderRadius.large ? {
        large: null
    } : value == BorderRadius.small ? {
        small: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CardStyle): {
    shadow: null;
} | {
    flat: null;
} | {
    glass: null;
} {
    return value == CardStyle.shadow ? {
        shadow: null
    } : value == CardStyle.flat ? {
        flat: null
    } : value == CardStyle.glass ? {
        glass: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Frequency): {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == Frequency.monthly ? {
        monthly: null
    } : value == Frequency.daily ? {
        daily: null
    } : value == Frequency.weekly ? {
        weekly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
